#!/usr/bin/env ruby
require 'json'
file_name = '/home/paul/bin/weather.json'

# the following string was obtainedy by https://developer.yahoo.com/weather/

`wget 'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22half%20moon%20bay%2C%20ca%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys' --output-document=#{file_name} 2>/dev/null`
xyz = JSON.parse File.read file_name
puts xyz['query']['results']['channel']['item']['forecast'][0]['text']
